version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"       # MinIO API
      - "9001:9001"       # MinIO Console
    environment:
      MINIO_ROOT_USER: miniodomain
      MINIO_ROOT_PASSWORD: miniodomain123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
